// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCT8yv2Na6KXwosnk0ZsLAsnSCLJeHesFM',
    appId: '1:957398913259:web:0949a656745a4b2d866eae',
    messagingSenderId: '957398913259',
    projectId: 'authentication-example-416b4',
    authDomain: 'authentication-example-416b4.firebaseapp.com',
    storageBucket: 'authentication-example-416b4.appspot.com',
    measurementId: 'G-CM61FFY7Q4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwzt1J2i7PNJJ8PlWytgaS5-WIOjse-6g',
    appId: '1:957398913259:android:867970dcb0088971866eae',
    messagingSenderId: '957398913259',
    projectId: 'authentication-example-416b4',
    storageBucket: 'authentication-example-416b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8uSjuHtji8L--5bLBAN5Syyh44KUCRp8',
    appId: '1:957398913259:ios:3ea63b65b333dab8866eae',
    messagingSenderId: '957398913259',
    projectId: 'authentication-example-416b4',
    storageBucket: 'authentication-example-416b4.appspot.com',
    iosClientId: '957398913259-3k2abc6uneka8q7h9a9al3h1niefn99d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuthentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8uSjuHtji8L--5bLBAN5Syyh44KUCRp8',
    appId: '1:957398913259:ios:3ea63b65b333dab8866eae',
    messagingSenderId: '957398913259',
    projectId: 'authentication-example-416b4',
    storageBucket: 'authentication-example-416b4.appspot.com',
    iosClientId: '957398913259-3k2abc6uneka8q7h9a9al3h1niefn99d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseAuthentication',
  );
}
